### ISSUE TITLE
Sidebar: Form title should be aligned in all resolutions.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Dr-Patrick-Briggs#101]
![image](https://cloud.githubusercontent.com/assets/11186313/16827217/ed45c3c6-49b6-11e6-87de-1f6f8cf2fccc.png)

**Comment by r-pochanakit** [comment]
![image](https://cloud.githubusercontent.com/assets/18692070/16830517/be51cc46-49c9-11e6-8318-afadb7713136.png)
