### ISSUE TITLE
Footer - Update text "Contact" to "Contact Us"

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Dr-Patrick-Briggs#11]
![image](https://cloud.githubusercontent.com/assets/18587097/16257795/be527336-3884-11e6-9748-daceb39f94e7.png)

**Comment by r-pochanakit** [comment]
Use Contact instead Contact Us as per design brief.
![image](https://cloud.githubusercontent.com/assets/18692070/16825725/530b0740-49a1-11e6-93ec-c066292f488d.png)
