### ISSUE TITLE
F&A page - Page title should be "F&A" or not? If yes, please update navigation.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Dr-Patrick-Briggs#36]
![image](https://cloud.githubusercontent.com/assets/18587097/16297414/f8f4bee6-395a-11e6-9cad-d0f9978040ba.png)

**Comment by r-pochanakit** [comment]
It should be FAQ as per sitemap
![image](https://cloud.githubusercontent.com/assets/18692070/16475428/b9e1a2f2-3ea8-11e6-815d-48d634e0081f.png)
