### ISSUE TITLE
Project Scope - Procedures Single: There is no video section on sidebar.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Dr-Patrick-Briggs#57]
![image](https://cloud.githubusercontent.com/assets/18587097/16370962/d48c9d42-3c6d-11e6-9324-da30e599931b.png)

**Comment by r-pochanakit** [comment]
It displayed on Procedures Single page.
![image](https://cloud.githubusercontent.com/assets/18692070/16612109/72d378cc-438f-11e6-899d-f4e6772298be.png)
