### ISSUE TITLE
Tablet - Inner page: Content is broken so please have the content displayed in 1 column.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Dr-Patrick-Briggs#84]
![image](https://cloud.githubusercontent.com/assets/18587097/16401376/31763ef0-3d0e-11e6-93aa-1ae3f493cd08.png)

**Comment by roseliesromeo** [comment]
Please apply fixes from 640 and below.
![image](https://cloud.githubusercontent.com/assets/11186313/16826929/3c9e65f2-49b4-11e6-91d3-9d6d32f49966.png)

**Comment by r-pochanakit** [comment]
Should apply fixes from 767 px and below because 640 px is in range 481-767 of boostrap media query. 
![image](https://cloud.githubusercontent.com/assets/18692070/16861018/21a74936-4a67-11e6-9a9c-82c96170e53b.png)
