### ISSUE TITLE
Mobile - Contact: Please have the form displayed in 1 column

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Dr-Patrick-Briggs#89]
![image](https://cloud.githubusercontent.com/assets/18587097/16402027/6df1ccd2-3d13-11e6-8c36-9ca57a84effd.png)

**Comment by roseliesromeo** [comment]
Inconsistent field width upon error on submission from 767px and below
![image](https://cloud.githubusercontent.com/assets/11186313/16826555/d11ca882-49b0-11e6-8f01-e26748c9fba5.png)

![image](https://cloud.githubusercontent.com/assets/11186313/16826564/ece04934-49b0-11e6-9011-45fbaaf74e6e.png)
