### ISSUE TITLE
Non surgical listing: Buttons, title and images should be aligned in grid view.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Dr-Patrick-Briggs#98]
![image](https://cloud.githubusercontent.com/assets/11186313/16827170/85f613f6-49b6-11e6-8953-fe28226aa1b5.png)

**Comment by r-pochanakit** [comment]
![image](https://cloud.githubusercontent.com/assets/18692070/16829944/154d5cbc-49c6-11e6-9cf8-3d093670a6ce.png)
